### ISSUE TITLE
Cannot read LAS 1.4, point data record format 6

### ISSUE THREAD

**Issue by pglira** [plitkey/matlas_tools#1]
Hi! 

First, thanks for sharing your code!

I have a problem with a LAS 1.4, (record format 6) file. The gps_time field returned by the las2mat function is a vector in which each element is zero. The las file was created by OPALS (http://www.geo.tuwien.ac.at/opals/).

Do you have an idea what may be the problem?

You can download the test file here:
https://www.dropbox.com/s/ybi5hgllprls2q9/test.las?dl=0

Thanks,
Philipp

**Comment by plitkey** [comment]
Hei,

Thanks for contacting me! I have never had point data record format 6 before, so thanks for sharing. The weird thing is that I could read it with

> > max(str.gps_time)

ans =   5.1252e+04

> > min(str.gps_time)

ans =   5.1242e+04

in my Linux Matlab, the LAStools version could be different in the Windows version, but the code is the same. I'm spending the rest of the day in windows, so I'll see what happens there.

Best regards,

Paula

**Comment by pglira** [comment]
Ok, thanks for checking it! I don't know if this can help, but with the lasdata function of Matlab FEX (http://www.mathworks.com/matlabcentral/fileexchange/48073-las-file-reader-writer) the gps_time can be read:

```
x = lasdata('test.las');
x.get_gps_time;
```

However, I prefer your functions, so it would be great if you can help me.

**Comment by plitkey** [comment]
Hello again,

This seems to work fine in the 64 bit versions, which are new, the 32 bit version gives zeros as you described. The 32 bit binaries are older with old LAStools version. Unfortunately, I was not able to quickly fix the problem by just compiling the library and the mex functions in a 32 bit system. We'll keep it in mind however that also 32 bit versions need updating.

**Comment by pglira** [comment]
You're right! With the x64 mex-file I'm getting the correct values. Thanks a lot!
